### ISSUE TITLE
`SnapConfig` raises a `KeyError` when the app is not running in a snap.

### ISSUE THREAD

**Issue by lengau** [albertodonato/snap-helpers#21]
When creating various top-level classes (Snap, SnapConfig) from outside of a snap, an unintuitive `KeyError` is raised:

```
$ python
Python 3.10.15 (main, Sep  7 2024, 18:35:38) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import snaphelpers
>>> snaphelpers.Snap()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lengau/Work/Code/craft-application/.venv/lib/python3.10/site-packages/snaphelpers/_snap.py", line 54, in __init__
    self.environ = SnapEnviron(environ=environ)
  File "/home/lengau/Work/Code/craft-application/.venv/lib/python3.10/site-packages/snaphelpers/_env.py", line 48, in __init__
    self._env["SNAP"] = environ["SNAP"]
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'SNAP'
>>> snaphelpers.SnapConfig()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lengau/Work/Code/craft-application/.venv/lib/python3.10/site-packages/snaphelpers/_conf.py", line 103, in __init__
    self._snapctl = snapctl or SnapCtl()
  File "/home/lengau/Work/Code/craft-application/.venv/lib/python3.10/site-packages/snaphelpers/_ctl.py", line 79, in __init__
    env = SnapEnviron()
  File "/home/lengau/Work/Code/craft-application/.venv/lib/python3.10/site-packages/snaphelpers/_env.py", line 48, in __init__
    self._env["SNAP"] = environ["SNAP"]
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'SNAP'
>>> snaphelpers.SnapCtl()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lengau/Work/Code/craft-application/.venv/lib/python3.10/site-packages/snaphelpers/_ctl.py", line 79, in __init__
    env = SnapEnviron()
  File "/home/lengau/Work/Code/craft-application/.venv/lib/python3.10/site-packages/snaphelpers/_env.py", line 48, in __init__
    self._env["SNAP"] = environ["SNAP"]
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'SNAP'
```

It would be clearer if this raised an exception telling the user that the app doesn't appear to be running as a snap.

**Comment by albertodonato** [comment]
FWIW `snaphelpers.is_snap` is the intended way to check if the app is running in a snap, creation of snap-related objects should be done under this check

**Comment by lengau** [comment]
Thanks for letting me know. I've adjusted my usage and created two PRs:

- https://github.com/albertodonato/snap-helpers/pull/22 provides a more specific error message if the provided environment is not a snap
- https://github.com/albertodonato/snap-helpers/pull/23 documents the `is_snap` function (I didn't see it in the docs, which was why I wasn't using it.)
